services:
  app:
    build: .
    container_name: student-management-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
volumes:
  pgdata: